export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_SIDEBAR_ACTIVE_MENU = 'SET_SIDEBAR_ACTIVE_MENU';

export const SET_MAP_VIEWPORT = 'SET_MAP_VIEWPORT';
export const SET_MAP_WIDTH_HEIGHT = 'SET_MAP_WIDTH_HEIGHT';
export const SET_MAP_MINIMIZED = 'SET_MAP_MINIMIZED';

export const SET_VENUES = 'SET_VENUES';
export const SET_VENUES_SELECTED = 'SET_VENUES_SELECTED';